apiVersion: 1

# InfluxDB Data Source Configuration
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: mms
      defaultBucket: assets
      tlsSkipVerify: true
      httpMode: POST
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
    editable: true
    isDefault: false

  # InfluxDB with SQL support (via Flight SQL)
  - name: InfluxDB-SQL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: SQL
      organization: mms
      defaultBucket: assets
      tlsSkipVerify: true
      httpMode: POST
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
    editable: true
    isDefault: false
